dataset: cifar100
net_type: transformer
depth: 9
patch_size: 4
embedding_size: 512
batch_size: 64

epochs: 300
batch_size: 64
lr: 0.25
momentum: 0.9

gradient_clip: 0
weight_decay: 0.0001

cutmix:
  beta: 1.0
  prob: 0.5
  num: 1

cutout: 0
